[package]
name = "eco"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.4.0", features = ["json", "charset"] }
