name: Test and Compile
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup the Project
        run: make setup
      - name: Build the Project
        run: cargo build --manifest-path=lang/Cargo.toml
      - name: Run Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: cargo build --manifest-path=lang/Cargo.toml
